### ISSUE TITLE
Error while compilling

### ISSUE THREAD

**Issue by bengris32** [LineageOS/android_kernel_oneplus_sdm845#1]
../../../../../../kernel/oneplus/sdm845/fs/ext4/page-io.c: In function 'ext4_bio_write_page':
../../../../../../kernel/oneplus/sdm845/fs/ext4/page-io.c:473:2: error: this 'if' clause does not guard... [-Werror=misleading-indentation]
  if (!fscrypt_using_hardware_encryption(inode))
  ^~
../../../../../../kernel/oneplus/sdm845/fs/ext4/page-io.c:476:3: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'if'
   if (IS_ERR(data_page)) {
   ^~
cc1: all warnings being treated as errors
make[3]: *** [/hdd/android/lineage/kernel/oneplus/sdm845/scripts/Makefile.build:339: fs/ext4/page-io.o] Error 1
make[2]: *** [/hdd/android/lineage/kernel/oneplus/sdm845/scripts/Makefile.build:653: fs/ext4] Error 2
make[1]: *** [/hdd/android/lineage/kernel/oneplus/sdm845/Makefile:1086: fs] Error 2

**Comment by luk1337** [comment]
Not really broken. You're just using newer compiler that actually warns about misleading indentation. Just fix it yourself, it's easy.

**Comment by bengris32** [comment]
> Not really broken. You're just using newer compiler that actually warns about misleading indentation. Just fix it yourself, it's easy.

Ah ok, thanks!
